import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-blue-600 text-white px-6 py-3 shadow flex flex-wrap gap-4 items-center">
          <a href="/Auth" className="font-bold hover:underline">Login</a>
          <span className="mx-4 border-l border-white h-6"></span>
          <a href="/patient/PatientDashboard" className="font-bold hover:underline">Patient Dashboard</a>
          <a href="/patient/PatientProfile" className="hover:underline">Patient Profile</a>
          <a href="/patient/PatientAppointmentCreate" className="hover:underline">Appointment Create</a>
          <a href="/patient/PatientAppointmentList" className="hover:underline">Appointment List</a>
          <a href="/patient/PatientMedicalRecordList" className="hover:underline">Medical Records</a>
          <a href="/patient/PatientBilling" className="hover:underline">Billing</a>
          <a href="/patient/PatientNotification" className="hover:underline">Notification</a>
          <a href="/patient/PatientAuditLog" className="hover:underline">Audit Log</a>
          <span className="mx-4 border-l border-white h-6"></span>
          <a href="/doctor/DoctorDashboard" className="font-bold hover:underline">Doctor Dashboard</a>
          <a href="/doctor/DoctorAppointmentList" className="hover:underline">Doctor Appointments</a>
          <a href="/doctor/DoctorPatientList" className="hover:underline">Doctor Patients</a>
          <a href="/doctor/DoctorMedicalRecordEdit" className="hover:underline">Medical Record Edit</a>
          <a href="/doctor/DoctorNotificationSend" className="hover:underline">Notification Send</a>
          <a href="/doctor/DoctorAnalytics" className="hover:underline">Analytics</a>
          <a href="/doctor/DoctorAuditLog" className="hover:underline">Audit Log</a>
          <span className="mx-4 border-l border-white h-6"></span>
          <a href="/admin/AdminDashboard" className="font-bold hover:underline">Admin Dashboard</a>
          <a href="/admin/AdminUserList" className="hover:underline">User List</a>
          <a href="/admin/AdminDataManagement" className="hover:underline">Data Management</a>
          <a href="/admin/AdminBilling" className="hover:underline">Billing</a>
          <a href="/admin/AdminNotificationConfig" className="hover:underline">Notification Config</a>
          <a href="/admin/AdminAuditBackup" className="hover:underline">Audit/Backup</a>
          <a href="/admin/AdminFileManager" className="hover:underline">File Manager</a>
          <a href="/admin/AdminReportAnalytics" className="hover:underline">Report Analytics</a>
        </nav>
        <main className="mt-6">{children}</main>
      </body>
    </html>
  );
}
